title: Advanced Product Owner MOOC
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: DARCBLUEAG/minimal-mistakes

# Outputting
permalink: /:categories/:title/
timezone: Europe/Berlin # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
exclude:
  - ".Ulysses-Group.plist"
  - ".Ulysses-Settings.plist"
  - .bundle
  - vendor
keep_files:
  - .git

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
  # _manual
  - scope:
      path: ""
      type: mooc
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "mooc"

collections:
  mooc:
    output: true
    permalink: /:collection/:path/

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
